export interface Strategy {
  id: number
  slug: string
  text: string
}

export const strategies: Strategy[] = [
  { id: 1, slug: "abandon-normal-instruments", text: "Abandon normal instruments" },
  { id: 2, slug: "accept-advice", text: "Accept advice" },
  { id: 3, slug: "accretion", text: "Accretion" },
  { id: 4, slug: "a-line-has-two-sides", text: "A line has two sides" },
  {
    id: 5,
    slug: "allow-an-easement-an-easement-is-the-abandonment-of-a-stricture",
    text: "Allow an easement (an easement is the abandonment of a stricture)",
  },
  { id: 6, slug: "are-there-sections-consider-transitions", text: "Are there sections? Consider transitions" },
  {
    id: 7,
    slug: "ask-people-to-work-against-their-better-judgement",
    text: "Ask people to work against their better judgement",
  },
  { id: 8, slug: "ask-your-body", text: "Ask your body" },
  { id: 9, slug: "be-dirty", text: "Be dirty" },
  { id: 10, slug: "breathe-more-deeply", text: "Breathe more deeply" },
  { id: 11, slug: "bridges-build-burn", text: "Bridges -build -burn" },
  { id: 12, slug: "cascades", text: "Cascades" },
  { id: 13, slug: "change-instrument-roles", text: "Change instrument roles" },
  { id: 14, slug: "childrens-voices-speaking-singing", text: "Children's voices -speaking -singing" },
  { id: 15, slug: "consider-different-fading-systems", text: "Consider different fading systems" },
  {
    id: 16,
    slug: "consult-other-sources-promising-unpromising",
    text: "Consult other sources -promising -unpromising",
  },
  {
    id: 17,
    slug: "convert-a-melodic-element-into-a-rhythmic-element",
    text: "Convert a melodic element into a rhythmic element",
  },
  { id: 18, slug: "courage", text: "Courage!" },
  { id: 19, slug: "cut-a-vital-connection", text: "Cut a vital connection" },
  { id: 20, slug: "decorate-decorate", text: "Decorate, decorate" },
  {
    id: 21,
    slug: "define-an-area-as-safe-and-use-it-as-an-anchor",
    text: "Define an area as 'safe' and use it as an anchor",
  },
  { id: 22, slug: "destroy-nothing-the-most-important-thing", text: "Destroy -nothing -the most important thing" },
  { id: 23, slug: "discard-an-axiom", text: "Discard an axiom" },
  { id: 24, slug: "disconnect-from-desire", text: "Disconnect from desire" },
  {
    id: 25,
    slug: "discover-the-recipes-you-are-using-and-abandon-them",
    text: "Discover the recipes you are using and abandon them",
  },
  { id: 26, slug: "distorting-time", text: "Distorting time" },
  { id: 27, slug: "do-nothing-for-as-long-as-possible", text: "Do nothing for as long as possible" },
  {
    id: 28,
    slug: "dont-be-afraid-of-things-because-theyre-easy-to-do",
    text: "Don't be afraid of things because they're easy to do",
  },
  { id: 29, slug: "dont-be-frightened-of-cliches", text: "Don't be frightened of clichés" },
  { id: 30, slug: "dont-be-frightened-to-display-your-talents", text: "Don't be frightened to display your talents" },
  { id: 31, slug: "dont-break-the-silence", text: "Don't break the silence" },
  { id: 32, slug: "dont-stress-one-thing-more-than-another", text: "Don't stress one thing more than another" },
  { id: 33, slug: "do-something-boring", text: "Do something boring" },
  { id: 34, slug: "do-the-washing-up", text: "Do the washing up" },
  { id: 35, slug: "do-the-words-need-changing", text: "Do the words need changing?" },
  { id: 36, slug: "do-we-need-holes", text: "Do we need holes?" },
  { id: 37, slug: "emphasise-differences", text: "Emphasise differences" },
  { id: 38, slug: "emphasise-repetitions", text: "Emphasise repetitions" },
  { id: 39, slug: "emphasise-the-flaws", text: "Emphasise the flaws" },
  { id: 40, slug: "faced-with-a-choice-do-both", text: "Faced with a choice, do both" },
  {
    id: 41,
    slug: "feedback-recordings-into-an-acoustic-situation",
    text: "Feedback recordings into an acoustic situation",
  },
  { id: 42, slug: "fill-every-beat-with-something", text: "Fill every beat with something" },
  { id: 43, slug: "from-nothing-to-something", text: "From nothing to something" },
  { id: 44, slug: "get-your-neck-massaged", text: "Get your neck massaged" },
  { id: 45, slug: "ghost-echoes", text: "Ghost echoes" },
  { id: 46, slug: "give-the-game-away", text: "Give the game away" },
  { id: 47, slug: "give-way-to-your-worst-impulse", text: "Give way to your worst impulse" },
  { id: 48, slug: "go-outside-shut-the-door", text: "Go outside. Shut the door." },
  {
    id: 49,
    slug: "go-to-an-extreme-move-back-to-a-more-comfortable-place",
    text: "Go to an extreme, move back to a more comfortable place",
  },
  { id: 50, slug: "honour-thy-error-as-a-hidden-intention", text: "Honour thy error as a hidden intention" },
  { id: 51, slug: "how-would-you-have-done-it", text: "How would you have done it?" },
  { id: 52, slug: "humanise-something-free-of-error", text: "Humanise something free of error" },
  {
    id: 53,
    slug: "imagine-the-music-as-a-moving-chain-or-caterpillar",
    text: "Imagine the music as a moving chain or caterpillar",
  },
  {
    id: 54,
    slug: "imagine-the-music-as-a-set-of-disconnected-events",
    text: "Imagine the music as a set of disconnected events",
  },
  {
    id: 55,
    slug: "in-total-darkness-or-in-a-very-large-room-very-quietly",
    text: "In total darkness, or in a very large room, very quietly",
  },
  { id: 56, slug: "infinitesimal-gradations", text: "Infinitesimal gradations" },
  { id: 57, slug: "into-the-impossible", text: "Into the impossible" },
  { id: 58, slug: "is-it-finished", text: "Is it finished?" },
  { id: 59, slug: "is-the-intonation-correct", text: "Is the intonation correct?" },
  { id: 60, slug: "is-there-something-missing", text: "Is there something missing?" },
  { id: 61, slug: "it-is-simply-a-matter-of-work", text: "It is simply a matter of work" },
  { id: 62, slug: "just-carry-on", text: "Just carry on" },
  {
    id: 63,
    slug: "left-channel-right-channel-centre-channel",
    text: "Left channel, right channel, centre channel",
  },
  { id: 64, slug: "listen-to-the-quiet-voice", text: "Listen to the quiet voice" },
  {
    id: 65,
    slug: "look-at-a-very-small-object-look-at-its-centre",
    text: "Look at a very small object, look at its centre",
  },
  { id: 66, slug: "look-at-the-order-in-which-you-do-things", text: "Look at the order in which you do things" },
  {
    id: 67,
    slug: "look-closely-at-the-most-embarrassing-details-and-amplify-them",
    text: "Look closely at the most embarrassing details and amplify them",
  },
  {
    id: 68,
    slug: "make-a-blank-valuable-by-putting-it-in-an-exquisite-frame",
    text: "Make a blank valuable by putting it in an exquisite frame",
  },
  {
    id: 69,
    slug: "make-an-exhaustive-list-of-everything-you-might-do-and-do-the-last-thing-on-the-list",
    text: "Make an exhaustive list of everything you might do and do the last thing on the list",
  },
  {
    id: 70,
    slug: "make-a-sudden-destructive-unpredictable-action-incorporate",
    text: "Make a sudden, destructive unpredictable action; incorporate",
  },
  {
    id: 71,
    slug: "the-most-important-thing-is-the-thing-most-easily-forgotten",
    text: "The most important thing is the thing most easily forgotten",
  },
  { id: 72, slug: "move-towards-the-unimportant", text: "Move towards the unimportant" },
  { id: 73, slug: "mute-and-continue", text: "Mute and continue" },
  { id: 74, slug: "not-building-a-wall-but-making-a-brick", text: "Not building a wall but making a brick" },
  { id: 75, slug: "nothing-is-real-until-it-is-nothing", text: "Nothing is real until it is nothing" },
  {
    id: 76,
    slug: "obtain-input-from-an-independent-collaborator-spoil-it",
    text: "Obtain input from an independent collaborator. Spoil it",
  },
  { id: 77, slug: "only-one-element-of-each-kind", text: "Only one element of each kind" },
  { id: 78, slug: "overtly-resist-change", text: "Overtly resist change" },
  { id: 79, slug: "put-in-earplugs", text: "Put in earplugs" },
  { id: 80, slug: "remember-those-quiet-evenings", text: "Remember those quiet evenings" },
  { id: 81, slug: "remove-a-restriction", text: "Remove a restriction" },
  { id: 82, slug: "remove-ambiguities-and-convert-to-specifics", text: "Remove ambiguities and convert to specifics" },
  { id: 83, slug: "remove-specifics-and-convert-to-ambiguities", text: "Remove specifics and convert to ambiguities" },
  { id: 84, slug: "repeat", text: "Repeat" },
  { id: 85, slug: "repetition-is-a-form-of-change", text: "Repetition is a form of change" },
  { id: 86, slug: "retrace-your-steps", text: "Retrace your steps" },
  { id: 87, slug: "revaluation-a-warm-feeling", text: "Revaluation (a warm feeling)" },
  {
    id: 88,
    slug: "short-circuit-describe-the-process-in-detail-then-remove-all-the-steps",
    text: "Short circuit (describe the process in detail, then remove all the steps)",
  },
  { id: 89, slug: "shut-the-door-and-listen-from-outside", text: "Shut the door and listen from outside" },
  { id: 90, slug: "simple-subtraction", text: "Simple subtraction" },
  {
    id: 91,
    slug: "state-the-problem-in-words-as-simply-as-possible",
    text: "State the problem in words as simply as possible",
  },
  { id: 92, slug: "take-a-break", text: "Take a break" },
  {
    id: 93,
    slug: "take-away-the-elements-in-order-of-importance",
    text: "Take away the elements in order of importance",
  },
  { id: 94, slug: "tape-your-mouth", text: "Tape your mouth" },
  { id: 95, slug: "the-inconsistency-principle", text: "The inconsistency principle" },
  { id: 96, slug: "the-tape-is-now-the-music", text: "The tape is now the music" },
  { id: 97, slug: "think-of-the-radio", text: "Think of the radio" },
  { id: 98, slug: "tidy-up", text: "Tidy up" },
  { id: 99, slug: "trust-in-the-you-of-now", text: "Trust in the you of now" },
  { id: 100, slug: "turn-it-upside-down", text: "Turn it upside down" },
  { id: 101, slug: "twist-the-spine", text: "Twist the spine" },
  { id: 102, slug: "use-an-old-idea", text: "Use an old idea" },
  { id: 103, slug: "use-an-unacceptable-colour", text: "Use an unacceptable colour" },
  { id: 104, slug: "use-fewer-notes", text: "Use fewer notes" },
  { id: 105, slug: "use-filters", text: "Use filters" },
  { id: 106, slug: "use-unqualified-people", text: "Use 'unqualified' people" },
  { id: 107, slug: "water", text: "Water" },
  {
    id: 108,
    slug: "what-are-you-really-thinking-about-just-now-incorporate",
    text: "What are you really thinking about just now? Incorporate",
  },
  { id: 109, slug: "what-is-the-simplest-thing-that-could-work", text: "What is the simplest thing that could work?" },
  { id: 110, slug: "work-at-a-different-speed", text: "Work at a different speed" },
  { id: 111, slug: "you-are-an-engineer", text: "You are an engineer" },
  { id: 112, slug: "you-can-only-make-one-dot-at-a-time", text: "You can only make one dot at a time" },
  { id: 113, slug: "your-mistake-was-a-hidden-intention", text: "Your mistake was a hidden intention" },
]

export function getAllStrategies(): Strategy[] {
  return strategies
}

export function getStrategyBySlug(slug: string): Strategy | undefined {
  return strategies.find((s) => s.slug === slug)
}
